"""create case and legal corpus foundation

Revision ID: 8b1773dcd131
Revises:
Create Date: 2026-08-22 15:13:16.362541
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8b1773dcd131"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinics",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 200"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legal_documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("canonical_key", sa.String(length=120), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), server_default="RU", nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("issuer", sa.String(length=240), nullable=False),
        sa.Column("official_number", sa.String(length=80), nullable=True),
        sa.Column("adoption_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column("system_role", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("telegram_user_id > 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    op.create_table(
        "clinic_users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="ACTIVE", nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clinic_id", "id"),
        sa.UniqueConstraint("clinic_id", "user_id"),
    )
    op.create_index(
        "ix_clinic_users_resolution",
        "clinic_users",
        ["user_id", "status", "clinic_id"],
        unique=False,
    )
    op.create_table(
        "legal_sources",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_key", sa.String(length=80), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("allowed_hosts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trust_level", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key", "revision"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id", "actor_membership_id"],
            ["clinic_users.clinic_id", "clinic_users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_tenant_time",
        "audit_events",
        ["clinic_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("case_no", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="COLLECTING", nullable=False),
        sa.Column(
            "intake_schema_version",
            sa.String(length=80),
            server_default="dental-case-intake.v1",
            nullable=False,
        ),
        sa.Column("primary_incident_type", sa.String(length=50), nullable=True),
        sa.Column(
            "incident_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=True),
        sa.Column("incident_date", sa.Date(), nullable=True),
        sa.Column("claim_date", sa.Date(), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("row_version > 0"),
        sa.ForeignKeyConstraint(
            ["clinic_id", "created_by_membership_id"],
            ["clinic_users.clinic_id", "clinic_users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_no"),
        sa.UniqueConstraint("clinic_id", "id"),
    )
    op.create_index(
        "ix_cases_tenant_updated", "cases", ["clinic_id", "updated_at", "id"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=80), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="IN_PROGRESS", nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id", "actor_membership_id"],
            ["clinic_users.clinic_id", "clinic_users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "actor_membership_id", "key"),
    )
    op.create_table(
        "legal_versions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("source_external_id", sa.String(length=120), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("version_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "approval_state", sa.String(length=30), server_default="REVIEW_REQUIRED", nullable=False
        ),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_mime_type", sa.String(length=100), nullable=False),
        sa.Column("raw_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("parser_version", sa.String(length=80), nullable=False),
        sa.Column(
            "regression_passed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("effective_to IS NULL OR effective_to > effective_from"),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["legal_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["legal_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "raw_sha256"),
        sa.UniqueConstraint("document_id", "version_no"),
    )
    op.create_index(
        "ix_legal_versions_resolution",
        "legal_versions",
        ["document_id", "approval_state", "effective_from"],
        unique=False,
    )
    op.create_table(
        "case_facts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("fact_key", sa.String(length=60), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("value_type", sa.String(length=30), nullable=False),
        sa.Column("value_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_ref_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "evidence_status", sa.String(length=20), server_default="UNVERIFIED", nullable=False
        ),
        sa.Column("recorded_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("supersedes_fact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("NOT (source_type = 'INFERENCE' AND evidence_status = 'CONFIRMED')"),
        sa.CheckConstraint("revision > 0"),
        sa.ForeignKeyConstraint(
            ["clinic_id", "case_id"], ["cases.clinic_id", "cases.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id", "recorded_by_membership_id"],
            ["clinic_users.clinic_id", "clinic_users.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_fact_id"],
            ["case_facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clinic_id", "case_id", "fact_key", "revision"),
    )
    op.create_index(
        "ix_case_facts_current",
        "case_facts",
        ["clinic_id", "case_id", "fact_key", "revision"],
        unique=False,
    )
    op.create_table(
        "case_reports",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("clinic_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("report_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("pdf_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=False),
        sa.Column("pdf_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("facts_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("pdf_size_bytes > 0"),
        sa.CheckConstraint("report_version > 0"),
        sa.ForeignKeyConstraint(
            ["clinic_id", "case_id"], ["cases.clinic_id", "cases.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id", "created_by_membership_id"],
            ["clinic_users.clinic_id", "clinic_users.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clinic_id", "case_id", "report_version"),
    )
    op.create_index(
        "ix_case_reports_latest",
        "case_reports",
        ["clinic_id", "case_id", "report_version"],
        unique=False,
    )
    op.create_table(
        "legal_fragments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("article", sa.String(length=80), nullable=True),
        sa.Column("part", sa.String(length=80), nullable=True),
        sa.Column("point", sa.String(length=80), nullable=True),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("structural_path", sa.Text(), nullable=False),
        sa.Column("fragment_text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["version_id"], ["legal_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "ordinal"),
    )
    op.create_index(
        "ix_legal_fragments_structure",
        "legal_fragments",
        ["version_id", "article", "part", "point"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        "ck_legal_sources_approved_actor",
        "legal_sources",
        "status <> 'APPROVED' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)",
    )
    op.create_index(
        "uq_legal_sources_current_approved",
        "legal_sources",
        ["source_key"],
        unique=True,
        postgresql_where=sa.text("status = 'APPROVED'"),
    )
    op.create_check_constraint(
        "ck_legal_versions_approved_gate",
        "legal_versions",
        "approval_state <> 'APPROVED' OR "
        "(approved_by IS NOT NULL AND approved_at IS NOT NULL AND regression_passed)",
    )
    op.execute(
        "ALTER TABLE legal_versions ADD CONSTRAINT ex_legal_versions_effective_overlap "
        "EXCLUDE USING gist "
        "(document_id WITH =, daterange(effective_from, effective_to, '[)') WITH &&) "
        "WHERE (approval_state = 'APPROVED')"
    )

    tenant_tables = (
        "cases",
        "case_facts",
        "case_reports",
        "audit_events",
        "idempotency_records",
    )
    for table_name in tenant_tables:
        op.execute(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY "tenant_isolation_{table_name}" ON "{table_name}" '
            "USING (clinic_id = nullif(current_setting('app.current_clinic_id', true), '')::uuid) "
            "WITH CHECK "
            "(clinic_id = nullif(current_setting('app.current_clinic_id', true), '')::uuid)"
        )

    op.execute(
        "CREATE FUNCTION prevent_immutable_mutation() RETURNS trigger "
        "LANGUAGE plpgsql AS $$ BEGIN "
        "RAISE EXCEPTION 'immutable legal record cannot be changed'; END $$"
    )
    op.execute(
        "CREATE TRIGGER case_facts_immutable BEFORE UPDATE OR DELETE ON case_facts "
        "FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation()"
    )
    op.execute(
        "CREATE TRIGGER case_reports_immutable BEFORE UPDATE OR DELETE ON case_reports "
        "FOR EACH ROW EXECUTE FUNCTION prevent_immutable_mutation()"
    )
    op.execute(
        "CREATE VIEW production_legal_fragments AS "
        "SELECT f.id AS fragment_id, f.version_id, v.document_id, f.article, f.part, "
        "f.point, f.structural_path, f.fragment_text, f.text_sha256, v.effective_from, "
        "v.effective_to, v.source_url, v.raw_sha256 "
        "FROM legal_fragments f "
        "JOIN legal_versions v ON v.id = f.version_id "
        "JOIN legal_sources s ON s.id = v.source_id "
        "WHERE v.approval_state = 'APPROVED' AND s.status = 'APPROVED'"
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS production_legal_fragments")
    op.execute("DROP TRIGGER IF EXISTS case_reports_immutable ON case_reports")
    op.execute("DROP TRIGGER IF EXISTS case_facts_immutable ON case_facts")
    op.execute("DROP FUNCTION IF EXISTS prevent_immutable_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_legal_fragments_structure", table_name="legal_fragments")
    op.drop_table("legal_fragments")
    op.drop_index("ix_case_reports_latest", table_name="case_reports")
    op.drop_table("case_reports")
    op.drop_index("ix_case_facts_current", table_name="case_facts")
    op.drop_table("case_facts")
    op.drop_index("ix_legal_versions_resolution", table_name="legal_versions")
    op.drop_table("legal_versions")
    op.drop_table("idempotency_records")
    op.drop_index("ix_cases_tenant_updated", table_name="cases")
    op.drop_table("cases")
    op.drop_index("ix_audit_events_tenant_time", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("legal_sources")
    op.drop_index("ix_clinic_users_resolution", table_name="clinic_users")
    op.drop_table("clinic_users")
    op.drop_table("users")
    op.drop_table("legal_documents")
    op.drop_table("clinics")
    # ### end Alembic commands ###
